config/routes.rb
Rails.application.routes.draw do

  resources :answers
  resources :questions

  root 'home#index'

  get '/about' => 'home#about'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include HasGravatar

  belongs_to :question
end

app/models/concerns/has_gravatar.rb
module HasGravatar
  def gravatar
    # "http://www.gravatar.com/avatar/#{Digest::MD5.hexidigest(email)}"
    "http://www.gravatar.com/avatar/424242"
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  include HasGravatar

  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    question = Question.find(params[:answer][:question_id])
    answer = question.answers.create(answer_params)

    QuestionAuthorMailer.notify_question_author(answer).deliver_later

    session[:current_user_email] = answer_params[:email]
    redirect_to question
  end

  private
  def answer_params
    params.require(:answer).permit(:email, :body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @questions = Question.order(created_at: :desc).all
  end

  def about
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.order(created_at: :desc)
  end

  def create
    Question.create(question_params)
    session[:current_user_email] = question_params[:email]
    redirect_to root_path
  end

  private
  def question_params
    params.require(:question).permit(:email, :body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user_email
    session[:current_user_email] || 'No email is saved yet...'
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/about.html.erb
<h1>About us:</h1>
<p>Not using Rails Generator</p>

app/views/home/index.html.erb
<div class="lead well">
  <h4>The Universe is the totality of everything that exists, has existed, or ever will exist.</h4>
  <small>This is a Q&A site about anything in the Universe.</small>
</div>

<div class="container">
  <div class="questions" data-ng-controller="QuestionController">
    <% @questions.each do |question| %>
        <div class="media" data-ng-click="viewAnswers('<%= question_path(question) %>')">
          <div class="media-left">
            <a href="#">
              <img class="media-object" src="<%= question.gravatar %>">
            </a>
          </div>
          <div class="media-body">
            <h4 class="media-heading"><%= question.email %> asked:</h4>
            <div class="time hidden-xs">
              <small><cite><%= time_ago_in_words question.created_at %> ago</cite></small>
            </div>
            <div>
              <%= truncate question.body, length: 100 %>
            </div>
            <div class="answer-btn hidden-xs">
              <a href="<%= question_path(question) %>" class="btn btn-success btn-xs">View Answers</a>
            </div>
          </div>
        </div>
    <% end %>
  </div>

  <% if @questions.empty? %>
      <div class="alert alert-info">Nothing here yet, be the first one to ask?</div>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Question and Answer Forum</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
        integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
          integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
          crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
</head>
<body data-ng-app="qna-app">

  <%= render 'partials/navbar' %>

  <div class="container">
    <%= yield %>
  </div>

  <%= render 'partials/new_question_form' %>

</body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button"
              class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Home</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <div class="navbar-text"><%= current_user_email %></div>
        </li>
        <li class="active">
          <form>
            <a href="#"
               class="btn btn-success navbar-btn btn-sm"
               data-toggle="modal"
               data-target="#new-question-modal">Ask Question</a>
          </form>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/partials/_new_answer_form.html.erb
<div class="modal fade" id="new-answer-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">New Answer</h4>
      </div>
      <!--<form class="form-horizontal" action="/answers" method="POST">-->
      <%= form_for :answer, url: '/answers', html: {class: 'form-horizontal'} do %>
          <input type="hidden" name="answer[question_id]" value="<%= @question.id %>">
          <div class="modal-body">
            <div class="form-group">
              <label for="inputEmail" class="col-sm-2 control-label">Email</label>
              <div class="col-sm-10">
                <input type="email"
                       class="form-control"
                       id="inputEmail"
                       name="answer[email]"
                       placeholder="Email"
                       value="<%= current_user_email %>"
                       required>
              </div>
            </div>
            <div class="form-group">
              <label for="inputAnswer" class="col-sm-2 control-label">Answer</label>
              <div class="col-sm-10">
              <textarea id="inputAnswer" name="answer[body]" class="form-control"
                        placeholder="What is your answer?" required></textarea>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
      <% end %>
      <!--</form>-->
    </div>
  </div>
</div>

app/views/partials/_new_question_form.html.erb
<div class="modal fade" id="new-question-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">New Question</h4>
      </div>
      <!--<form class="form-horizontal" action="/questions" method="POST">-->
      <%= form_for :question, url: '/questions', html: {class: 'form-horizontal'} do %>
          <div class="modal-body">
            <div class="form-group">
              <label for="inputEmail" class="col-sm-2 control-label">Email</label>
              <div class="col-sm-10">
                <input type="email"
                       class="form-control"
                       id="inputEmail"
                       name="question[email]"
                       placeholder="Email"
                       value="<%= current_user_email %>"
                       required>
              </div>
            </div>
            <div class="form-group">
              <label for="inputQuestion" class="col-sm-2 control-label">Question</label>
              <div class="col-sm-10">
              <textarea class="form-control" id="inputQuestion" name="question[body]" placeholder="What would you like to know"
                        required></textarea>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
      <% end %>
      <!--</form>-->
    </div>
  </div>
</div>

app/views/questions/show.html.erb
<div class="container">

  <div class="lead well">
    <div class="media">
      <div class="media-left">
        <a href="#">
          <img class="media-object" src="<%= @question.gravatar %>">
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading"><%= @question.email %> asked:</h4>
        <%= @question.body %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <div>
        <button type="button"
                class="btn btn-success btn-sm"
                data-toggle="modal"
                data-target="#new-answer-modal">Submit New Answer
        </button>
      </div>

      <%= render 'partials/new_answer_form' %>

      <div class="answers">
        <% @answers.each do |answer| %>
            <div class="media">
              <div class="media-left">
                <a href="#">
                  <img class="media-object" src="<%= answer.gravatar %>">
                </a>
              </div>
              <div class="media-body">
                <h4 class="media-heading"><%= answer.email %> answered:</h4>
                <div class="time">
                  <small><cite><%= time_ago_in_words answer.created_at %> ago</cite></small>
                </div>
                <%= answer.body %>
              </div>
            </div>
        <% end %></div>

      <% if @answers.empty? %>
          <div class="alert alert-info alert-sm">Nothing here yet, be the first one to answer?</div>
      <% end %>

    </div>
  </div>
</div>